### ISSUE TITLE
API Gateway Wildcard Route?

### ISSUE THREAD

**Issue by spencer516** [damon-lanphear/ember-deploy-dynamodb#5]
We were toying around with the idea of using DynamoDB + Lambda and came across this project. I've been testing it out, but I've got one roadblock that hopefully you might be able to provide some insight for. 

As far as I can tell, there is no wildcard support in the API Gateway — so, if a user has navigated away from the index page on my Ember app and then does a hard refresh, how do I still have the `/` resource on API Gateway handle that request? 

I've read some suggestions that I could just create a bunch of nested resources made up of only parameter paths. (i.e.: `/{param1}/{param2}/{param3}/{param4}`) — and then configure each of those to use the same lambda function.

Assuming that you are using this, how are you handling this with the API Gateway? Thanks!

(Related discussion: https://forums.aws.amazon.com/thread.jspa?messageID=689700&#689700 )

**Comment by amay** [comment]
Hi @spencer516, sadly we are just doing the nested resource approach. Absolutely less than ideal, but it works until API Gateway handles wildcards.

**Comment by spencer516** [comment]
Thanks!
